from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(39, 89, 80, 255), stop:1 rgba(38, 1, 1, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_engen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_engen.setEnabled(True)
        self.btn_engen.setGeometry(QtCore.QRect(5, 5, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_engen.setFont(font)
        self.btn_engen.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_engen.setStyleSheet("background-color: rgba(39, 89, 80, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: none")
        self.btn_engen.setObjectName("btn_engen")
        self.btn_topology = QtWidgets.QPushButton(self.centralwidget)
        self.btn_topology.setEnabled(True)
        self.btn_topology.setGeometry(QtCore.QRect(5, 90, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_topology.setFont(font)
        self.btn_topology.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_topology.setStyleSheet("background-color: rgba(39, 89, 80, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: none")
        self.btn_topology.setObjectName("btn_topology")
        self.btn_pam = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pam.setEnabled(True)
        self.btn_pam.setGeometry(QtCore.QRect(5, 175, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_pam.setFont(font)
        self.btn_pam.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_pam.setStyleSheet("background-color: rgba(39, 89, 80, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: none")
        self.btn_pam.setObjectName("btn_pam")
        self.btn_math = QtWidgets.QPushButton(self.centralwidget)
        self.btn_math.setEnabled(True)
        self.btn_math.setGeometry(QtCore.QRect(5, 260, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_math.setFont(font)
        self.btn_math.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_math.setStyleSheet("background-color: rgba(39, 89, 80, 150);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: none")
        self.btn_math.setObjectName("btn_math")
        self.btn_kd = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kd.setEnabled(True)
        self.btn_kd.setGeometry(QtCore.QRect(70, 530, 150, 150))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_kd.setFont(font)
        self.btn_kd.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_kd.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 96), stop:0.895522 rgba(105, 164, 159, 161));\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 75px;\n"
"border: none")
        self.btn_kd.setObjectName("btn_kd")
        self.text_manager = QtWidgets.QLabel(self.centralwidget)
        self.text_manager.setGeometry(QtCore.QRect(1070, 650, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(26)
        self.text_manager.setFont(font)
        self.text_manager.setStyleSheet("background-color: rgba(39, 89, 80, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_manager.setTextFormat(QtCore.Qt.AutoText)
        self.text_manager.setObjectName("text_manager")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 600, 1001, 91))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(39, 89, 80, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(310, 5, 965, 580))
        self.stackedWidget.setStyleSheet("background-color: rgba(65, 191, 179,70);\n"
"border-radius: 10px;\n"
"border: none")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("background-color: rgba(163, 171, 120, 70);\n"
"border-radius: 10px;\n"
"border: none")
        self.page.setObjectName("page")
        self.text_arch_eng = QtWidgets.QLabel(self.page)
        self.text_arch_eng.setGeometry(QtCore.QRect(760, 0, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.text_arch_eng.setFont(font)
        self.text_arch_eng.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_arch_eng.setObjectName("text_arch_eng")
        self.textEdit_eng = QtWidgets.QTextEdit(self.page)
        self.textEdit_eng.setGeometry(QtCore.QRect(180, 120, 751, 231))
        self.textEdit_eng.setStyleSheet("color: rgb(255, 255, 255);")
        self.textEdit_eng.setObjectName("textEdit_eng")
        self.lineEdit_eng = QtWidgets.QLineEdit(self.page)
        self.lineEdit_eng.setGeometry(QtCore.QRect(180, 70, 751, 31))
        self.lineEdit_eng.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_eng.setObjectName("lineEdit_eng")
        self.text_enter_eng_1 = QtWidgets.QLabel(self.page)
        self.text_enter_eng_1.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.text_enter_eng_1.setFont(font)
        self.text_enter_eng_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_enter_eng_1.setObjectName("text_enter_eng_1")
        self.text_enter_eng_2 = QtWidgets.QLabel(self.page)
        self.text_enter_eng_2.setGeometry(QtCore.QRect(20, 120, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.text_enter_eng_2.setFont(font)
        self.text_enter_eng_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_enter_eng_2.setObjectName("text_enter_eng_2")
        self.btn_check_eng = QtWidgets.QPushButton(self.page)
        self.btn_check_eng.setGeometry(QtCore.QRect(570, 510, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.btn_check_eng.setFont(font)
        self.btn_check_eng.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_check_eng.setObjectName("btn_check_eng")
        self.btn_send_eng = QtWidgets.QPushButton(self.page)
        self.btn_send_eng.setGeometry(QtCore.QRect(780, 510, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.btn_send_eng.setFont(font)
        self.btn_send_eng.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_send_eng.setObjectName("btn_send_eng")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("background-color: rgba(129, 130, 116, 70);\n"
"border-radius: 10px;\n"
"border: none")
        self.page_2.setObjectName("page_2")
        self.text_modsim_topology = QtWidgets.QLabel(self.page_2)
        self.text_modsim_topology.setGeometry(QtCore.QRect(760, 0, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.text_modsim_topology.setFont(font)
        self.text_modsim_topology.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_modsim_topology.setObjectName("text_modsim_topology")
        self.btn_check_topology = QtWidgets.QPushButton(self.page_2)
        self.btn_check_topology.setGeometry(QtCore.QRect(570, 510, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.btn_check_topology.setFont(font)
        self.btn_check_topology.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_check_topology.setObjectName("btn_check_topology")
        self.text_enter_topology_2 = QtWidgets.QLabel(self.page_2)
        self.text_enter_topology_2.setGeometry(QtCore.QRect(20, 120, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.text_enter_topology_2.setFont(font)
        self.text_enter_topology_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_enter_topology_2.setObjectName("text_enter_topology_2")
        self.btn_send_topology = QtWidgets.QPushButton(self.page_2)
        self.btn_send_topology.setGeometry(QtCore.QRect(780, 510, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.btn_send_topology.setFont(font)
        self.btn_send_topology.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_send_topology.setObjectName("btn_send_topology")
        self.text_enter_topology_1 = QtWidgets.QLabel(self.page_2)
        self.text_enter_topology_1.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.text_enter_topology_1.setFont(font)
        self.text_enter_topology_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_enter_topology_1.setObjectName("text_enter_topology_1")
        self.lineEdit_topology = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_topology.setGeometry(QtCore.QRect(180, 70, 751, 31))
        self.lineEdit_topology.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_topology.setObjectName("lineEdit_topology")
        self.textEdit_topology = QtWidgets.QTextEdit(self.page_2)
        self.textEdit_topology.setGeometry(QtCore.QRect(180, 120, 751, 231))
        self.textEdit_topology.setStyleSheet("color: rgb(255, 255, 255);")
        self.textEdit_topology.setObjectName("textEdit_topology")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("background-color: rgba(80, 98, 102, 70);\n"
"border-radius: 10px;\n"
"border: none")
        self.page_3.setObjectName("page_3")
        self.text_enter_pam_1 = QtWidgets.QLabel(self.page_3)
        self.text_enter_pam_1.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.text_enter_pam_1.setFont(font)
        self.text_enter_pam_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_enter_pam_1.setObjectName("text_enter_pam_1")
        self.btn_check_pam = QtWidgets.QPushButton(self.page_3)
        self.btn_check_pam.setGeometry(QtCore.QRect(570, 510, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.btn_check_pam.setFont(font)
        self.btn_check_pam.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_check_pam.setObjectName("btn_check_pam")
        self.textEdit_pam = QtWidgets.QTextEdit(self.page_3)
        self.textEdit_pam.setGeometry(QtCore.QRect(180, 120, 751, 231))
        self.textEdit_pam.setStyleSheet("color: rgb(255, 255, 255);")
        self.textEdit_pam.setObjectName("textEdit_pam")
        self.lineEdit_pam = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_pam.setGeometry(QtCore.QRect(180, 70, 751, 31))
        self.lineEdit_pam.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_pam.setObjectName("lineEdit_pam")
        self.text_enter_pam_2 = QtWidgets.QLabel(self.page_3)
        self.text_enter_pam_2.setGeometry(QtCore.QRect(20, 120, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.text_enter_pam_2.setFont(font)
        self.text_enter_pam_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_enter_pam_2.setObjectName("text_enter_pam_2")
        self.btn_send_pam = QtWidgets.QPushButton(self.page_3)
        self.btn_send_pam.setGeometry(QtCore.QRect(780, 510, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.btn_send_pam.setFont(font)
        self.btn_send_pam.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_send_pam.setObjectName("btn_send_pam")
        self.text_spw_pam = QtWidgets.QLabel(self.page_3)
        self.text_spw_pam.setGeometry(QtCore.QRect(760, 0, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.text_spw_pam.setFont(font)
        self.text_spw_pam.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_spw_pam.setObjectName("text_spw_pam")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("background-color: rgba(193, 197, 115, 70);\n"
"border-radius: 10px;\n"
"border: none")
        self.page_4.setObjectName("page_4")
        self.text_mat_math = QtWidgets.QLabel(self.page_4)
        self.text_mat_math.setGeometry(QtCore.QRect(760, 0, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.text_mat_math.setFont(font)
        self.text_mat_math.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_mat_math.setObjectName("text_mat_math")
        self.lineEdit_math = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_math.setGeometry(QtCore.QRect(180, 70, 751, 31))
        self.lineEdit_math.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_math.setObjectName("lineEdit_math")
        self.textEdit_math = QtWidgets.QTextEdit(self.page_4)
        self.textEdit_math.setGeometry(QtCore.QRect(180, 120, 751, 231))
        self.textEdit_math.setStyleSheet("color: rgb(255, 255, 255);")
        self.textEdit_math.setObjectName("textEdit_math")
        self.text_enter_math_1 = QtWidgets.QLabel(self.page_4)
        self.text_enter_math_1.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.text_enter_math_1.setFont(font)
        self.text_enter_math_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_enter_math_1.setObjectName("text_enter_math_1")
        self.btn_send_math = QtWidgets.QPushButton(self.page_4)
        self.btn_send_math.setGeometry(QtCore.QRect(780, 510, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.btn_send_math.setFont(font)
        self.btn_send_math.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_send_math.setObjectName("btn_send_math")
        self.btn_check_math = QtWidgets.QPushButton(self.page_4)
        self.btn_check_math.setGeometry(QtCore.QRect(570, 510, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.btn_check_math.setFont(font)
        self.btn_check_math.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_check_math.setObjectName("btn_check_math")
        self.text_enter_math_2 = QtWidgets.QLabel(self.page_4)
        self.text_enter_math_2.setGeometry(QtCore.QRect(20, 120, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.text_enter_math_2.setFont(font)
        self.text_enter_math_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_enter_math_2.setObjectName("text_enter_math_2")
        self.stackedWidget.addWidget(self.page_4)
        self.btn_openApp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_openApp.setEnabled(True)
        self.btn_openApp.setGeometry(QtCore.QRect(220, 660, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_openApp.setFont(font)
        self.btn_openApp.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_openApp.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 96), stop:0.895522 rgba(105, 164, 159, 161));\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"border: none")
        self.btn_openApp.setObjectName("btn_openApp")
        self.btn_openWeb = QtWidgets.QPushButton(self.centralwidget)
        self.btn_openWeb.setEnabled(True)
        self.btn_openWeb.setGeometry(QtCore.QRect(20, 660, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_openWeb.setFont(font)
        self.btn_openWeb.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_openWeb.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 96), stop:0.895522 rgba(105, 164, 159, 161));\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"border: none")
        self.btn_openWeb.setObjectName("btn_openWeb")
        self.stackedWidget.raise_()
        self.btn_engen.raise_()
        self.btn_topology.raise_()
        self.btn_pam.raise_()
        self.btn_math.raise_()
        self.btn_kd.raise_()
        self.text_manager.raise_()
        self.label_2.raise_()
        self.btn_openApp.raise_()
        self.btn_openWeb.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_engen.setText(_translate("MainWindow", "конструкторский"))
        self.btn_topology.setText(_translate("MainWindow", "топология"))
        self.btn_pam.setText(_translate("MainWindow", "пам"))
        self.btn_math.setText(_translate("MainWindow", "математический"))
        self.btn_kd.setText(_translate("MainWindow", "кд"))
        self.text_manager.setText(_translate("MainWindow", "manager"))
        self.label_2.setText(_translate("MainWindow", "        Проект 868 «Создание концепции и пилотного образца комплексной системы автоматизированного проектирования (САПР) микроэлектронных и микромодульных устройств с использованием технологий цифровых двойников»"))
        self.text_arch_eng.setText(_translate("MainWindow", "Cadence I-Architect"))
        self.text_enter_eng_1.setText(_translate("MainWindow", "Введите данные:"))
        self.text_enter_eng_2.setText(_translate("MainWindow", "Введите данные:"))
        self.btn_check_eng.setText(_translate("MainWindow", "проверить"))
        self.btn_send_eng.setText(_translate("MainWindow", "отправить"))
        self.text_modsim_topology.setText(_translate("MainWindow", "ModelSim"))
        self.btn_check_topology.setText(_translate("MainWindow", "проверить"))
        self.text_enter_topology_2.setText(_translate("MainWindow", "Введите данные:"))
        self.btn_send_topology.setText(_translate("MainWindow", "отправить"))
        self.text_enter_topology_1.setText(_translate("MainWindow", "Введите данные:"))
        self.text_enter_pam_1.setText(_translate("MainWindow", "Введите данные:"))
        self.btn_check_pam.setText(_translate("MainWindow", "проверить"))
        self.text_enter_pam_2.setText(_translate("MainWindow", "Введите данные:"))
        self.btn_send_pam.setText(_translate("MainWindow", "отправить"))
        self.text_spw_pam.setText(_translate("MainWindow", "Cadence SPW2000"))
        self.text_mat_math.setText(_translate("MainWindow", "MatLab"))
        self.text_enter_math_1.setText(_translate("MainWindow", "Введите данные:"))
        self.btn_send_math.setText(_translate("MainWindow", "отправить"))
        self.btn_check_math.setText(_translate("MainWindow", "проверить"))
        self.text_enter_math_2.setText(_translate("MainWindow", "Введите данные:"))
        self.btn_openApp.setText(_translate("MainWindow", "test"))
        self.btn_openWeb.setText(_translate("MainWindow", "test"))

    def add_functions(self):
            self.btn_engen.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page))
            self.btn_topology.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_2))
            self.btn_pam.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_3))
            self.btn_math.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_4))
            self.btn_kd.clicked.connect(self.save_text)


    def save_text(self):
            with open('test.txt','w') as f:
                    my_text = self.lineEdit_eng.text()
                    my_text = my_text + "\n" + self.textEdit_eng.toPlainText()
                    my_text = my_text + "\n" + self.lineEdit_topology.text()
                    my_text = my_text + "\n" + self.textEdit_topology.toPlainText()
                    my_text = my_text + "\n" + self.lineEdit_pam.text()
                    my_text = my_text + "\n" + self.textEdit_pam.toPlainText()
                    my_text = my_text + "\n" + self.lineEdit_math.text()
                    my_text = my_text + "\n" + self.textEdit_math.toPlainText()
                    f.write(my_text)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
